// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseLine: typeof import('./src/components/BaseLine.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    SelectView: typeof import('./src/components/SelectView.vue')['default']
    YMSelect: typeof import('./src/components/YMSelect.vue')['default']
  }
}

export { }
